def multiply(x, y):
    try:
        return x * y
    except Exception as ex:
        print(f"Following error ocurred: {ex}")

